# -*- coding: utf-8 -*-
"""Python4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVNeQw8bLTrWTo3Tx9P7Clwi7NjE6hJ8
"""

m=[203,'hyd',370,True,'delhi',54,94,68]
m

m[1]

m[-6]

m[3:1]

m[3:5]

m[-6:]

m[-2:2]

m[-2::2]

m[1:3]

m.append(75)

m

m.remove(54)
m

m.insert(5,66)

m

m.insert(0,'delhi')
m

print(m)

m.append('India')

m

